<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Crear usuarios de prueba
        $users = [
            // Usuarios originales
            [
                'cod_us' => 'USR001',
                'nom_us' => 'Ithan',
                'app_us' => 'Escobar',      
                'apm_us' => 'Villegas', 
                'ema_us' => 'ithan@socialpet.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '79865412',
                'ubi_us' => 'Lima',         
                'tip_us' => 'usuario',      
                'est_us' => 'activo',       
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR002',
                'nom_us' => 'Glenda',
                'app_us' => 'Supa',        
                'apm_us' => 'Canamari', 
                'ema_us' => 'glenda@socialpet.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '78945612',
                'ubi_us' => 'La Paz',       
                'tip_us' => 'usuario',      
                'est_us' => 'activo',       
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR003',
                'nom_us' => 'Carlos',
                'app_us' => 'Meave',        
                'apm_us' => 'Choque', 
                'ema_us' => 'carlos@socialpet.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '73216548',
                'ubi_us' => 'La Paz',       
                'tip_us' => 'usuario',      
                'est_us' => 'activo',       
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR004',
                'nom_us' => 'Gladys Patricia',
                'app_us' => 'Layme',        
                'apm_us' => 'Mamani', 
                'ema_us' => 'gladys@socialpet.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '73214872',
                'ubi_us' => 'La Paz',       
                'tip_us' => 'usuario',      
                'est_us' => 'activo',       
                'is_admin' => false,
            ],
                        
            // 45 nuevos usuarios
            [
                'cod_us' => 'USR005',
                'nom_us' => 'Ana',
                'app_us' => 'Martínez',
                'apm_us' => 'García',
                'ema_us' => 'ana.martinez@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '61122334',
                'ubi_us' => 'Madrid',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR006',
                'nom_us' => 'Luis',
                'app_us' => 'Rodríguez',
                'apm_us' => 'Fernández',
                'ema_us' => 'luis.rodriguez@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '62233445',
                'ubi_us' => 'Barcelona',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR007',
                'nom_us' => 'María',
                'app_us' => 'González',
                'apm_us' => 'López',
                'ema_us' => 'maria.gonzalez@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '63344556',
                'ubi_us' => 'Valencia',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR008',
                'nom_us' => 'Javier',
                'app_us' => 'Sánchez',
                'apm_us' => 'Pérez',
                'ema_us' => 'javier.sanchez@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '64455667',
                'ubi_us' => 'Sevilla',
                'tip_us' => 'usuario',
                'est_us' => 'inactivo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR009',
                'nom_us' => 'Carmen',
                'app_us' => 'Ramírez',
                'apm_us' => 'Torres',
                'ema_us' => 'carmen.ramirez@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '65566778',
                'ubi_us' => 'Zaragoza',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR010',
                'nom_us' => 'David',
                'app_us' => 'Flores',
                'apm_us' => 'Rivera',
                'ema_us' => 'david.flores@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '66677889',
                'ubi_us' => 'Málaga',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR011',
                'nom_us' => 'Laura',
                'app_us' => 'Morales',
                'apm_us' => 'Ortega',
                'ema_us' => 'laura.morales@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '67788990',
                'ubi_us' => 'Murcia',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR012',
                'nom_us' => 'Pedro',
                'app_us' => 'Vargas',
                'apm_us' => 'Castillo',
                'ema_us' => 'pedro.vargas@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '68899001',
                'ubi_us' => 'Palma',
                'tip_us' => 'usuario',
                'est_us' => 'baneado',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR013',
                'nom_us' => 'Sofia',
                'app_us' => 'Ramos',
                'apm_us' => 'Cruz',
                'ema_us' => 'sofia.ramos@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '69900112',
                'ubi_us' => 'Bilbao',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR014',
                'nom_us' => 'Diego',
                'app_us' => 'Ortiz',
                'apm_us' => 'Mendoza',
                'ema_us' => 'diego.ortiz@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '61011223',
                'ubi_us' => 'Alicante',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR015',
                'nom_us' => 'Elena',
                'app_us' => 'Silva',
                'apm_us' => 'Rojas',
                'ema_us' => 'elena.silva@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '62122334',
                'ubi_us' => 'Córdoba',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR016',
                'nom_us' => 'Alejandro',
                'app_us' => 'Castro',
                'apm_us' => 'Guerrero',
                'ema_us' => 'alejandro.castro@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '63233445',
                'ubi_us' => 'Valladolid',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR017',
                'nom_us' => 'Paula',
                'app_us' => 'Nuñez',
                'apm_us' => 'Soto',
                'ema_us' => 'paula.nunez@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '64344556',
                'ubi_us' => 'Las Palmas',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR018',
                'nom_us' => 'Andrés',
                'app_us' => 'Díaz',
                'apm_us' => 'Peña',
                'ema_us' => 'andres.diaz@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '65455667',
                'ubi_us' => 'Granada',
                'tip_us' => 'usuario',
                'est_us' => 'inactivo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR019',
                'nom_us' => 'Natalia',
                'app_us' => 'Aguilar',
                'apm_us' => 'Reyes',
                'ema_us' => 'natalia.aguilar@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '66566778',
                'ubi_us' => 'Santander',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR020',
                'nom_us' => 'Ricardo',
                'app_us' => 'Molina',
                'apm_us' => 'Vega',
                'ema_us' => 'ricardo.molina@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '67677889',
                'ubi_us' => 'Gijón',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR021',
                'nom_us' => 'Valeria',
                'app_us' => 'Delgado',
                'apm_us' => 'Campos',
                'ema_us' => 'valeria.delgado@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '68788990',
                'ubi_us' => 'Badajoz',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR022',
                'nom_us' => 'Fernando',
                'app_us' => 'Herrera',
                'apm_us' => 'Fuentes',
                'ema_us' => 'fernando.herrera@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '69899001',
                'ubi_us' => 'Tenerife',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR023',
                'nom_us' => 'Isabel',
                'app_us' => 'Medina',
                'apm_us' => 'Blanco',
                'ema_us' => 'isabel.medina@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '60900112',
                'ubi_us' => 'Almería',
                'tip_us' => 'usuario',
                'est_us' => 'baneado',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR024',
                'nom_us' => 'Roberto',
                'app_us' => 'Vásquez',
                'apm_us' => 'León',
                'ema_us' => 'roberto.vasquez@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '61011223',
                'ubi_us' => 'Cádiz',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR025',
                'nom_us' => 'Daniela',
                'app_us' => 'Acosta',
                'apm_us' => 'Méndez',
                'ema_us' => 'daniela.acosta@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '62122334',
                'ubi_us' => 'Huelva',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR026',
                'nom_us' => 'Hugo',
                'app_us' => 'Paredes',
                'apm_us' => 'Salazar',
                'ema_us' => 'hugo.paredes@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '63233445',
                'ubi_us' => 'Lugo',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR027',
                'nom_us' => 'Cristina',
                'app_us' => 'Chávez',
                'apm_us' => 'Ponce',
                'ema_us' => 'cristina.chavez@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '64344556',
                'ubi_us' => 'Ourense',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR028',
                'nom_us' => 'Sergio',
                'app_us' => 'Zambrano',
                'apm_us' => 'Villalobos',
                'ema_us' => 'sergio.zambrano@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '65455667',
                'ubi_us' => 'Pamplona',
                'tip_us' => 'usuario',
                'est_us' => 'inactivo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR029',
                'nom_us' => 'Adriana',
                'app_us' => 'Cabrera',
                'apm_us' => 'Bermúdez',
                'ema_us' => 'adriana.cabrera@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '66566778',
                'ubi_us' => 'Logroño',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR030',
                'nom_us' => 'Gabriel',
                'app_us' => 'Figueroa',
                'apm_us' => 'Lara',
                'ema_us' => 'gabriel.figueroa@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '67677889',
                'ubi_us' => 'Burgos',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR031',
                'nom_us' => 'Mónica',
                'app_us' => 'Gallegos',
                'apm_us' => 'Escobar',
                'ema_us' => 'monica.gallegos@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '68788990',
                'ubi_us' => 'Salamanca',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR032',
                'nom_us' => 'Francisco',
                'app_us' => 'Valenzuela',
                'apm_us' => 'Montoya',
                'ema_us' => 'francisco.valenzuela@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '69899001',
                'ubi_us' => 'Lleida',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR033',
                'nom_us' => 'Beatriz',
                'app_us' => 'Guzmán',
                'apm_us' => 'Calderón',
                'ema_us' => 'beatriz.guzman@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '60900112',
                'ubi_us' => 'Tarragona',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR034',
                'nom_us' => 'Manuel',
                'app_us' => 'Rocha',
                'apm_us' => 'Franco',
                'ema_us' => 'manuel.rocha@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '61011223',
                'ubi_us' => 'Girona',
                'tip_us' => 'usuario',
                'est_us' => 'baneado',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR035',
                'nom_us' => 'Patricia',
                'app_us' => 'Trujillo',
                'apm_us' => 'Cortés',
                'ema_us' => 'patricia.trujillo@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '62122334',
                'ubi_us' => 'Ibiza',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR036',
                'nom_us' => 'Esteban',
                'app_us' => 'Quintero',
                'apm_us' => 'Palacios',
                'ema_us' => 'esteban.quintero@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '63233445',
                'ubi_us' => 'Marbella',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR037',
                'nom_us' => 'Julia',
                'app_us' => 'Olivera',
                'apm_us' => 'Márquez',
                'ema_us' => 'julia.olivera@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '64344556',
                'ubi_us' => 'León',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR038',
                'nom_us' => 'Oscar',
                'app_us' => 'Guerra',
                'apm_us' => 'Santana',
                'ema_us' => 'oscar.guerra@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '65455667',
                'ubi_us' => 'Albacete',
                'tip_us' => 'usuario',
                'est_us' => 'inactivo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR039',
                'nom_us' => 'Rosa',
                'app_us' => 'Mata',
                'apm_us' => 'Ibarra',
                'ema_us' => 'rosa.mata@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '66566778',
                'ubi_us' => 'Ciudad Real',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR040',
                'nom_us' => 'Pablo',
                'app_us' => 'Suárez',
                'apm_us' => 'Roldán',
                'ema_us' => 'pablo.suarez@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '67677889',
                'ubi_us' => 'Cuenca',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR041',
                'nom_us' => 'Lorena',
                'app_us' => 'Bustos',
                'apm_us' => 'Armijo',
                'ema_us' => 'lorena.bustos@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '68788990',
                'ubi_us' => 'Guadalajara',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR042',
                'nom_us' => 'Alberto',
                'app_us' => 'Jaramillo',
                'apm_us' => 'Vélez',
                'ema_us' => 'alberto.jaramillo@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '69899001',
                'ubi_us' => 'Toledo',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR043',
                'nom_us' => 'Teresa',
                'app_us' => 'Riojas',
                'apm_us' => 'Carvajal',
                'ema_us' => 'teresa.riojas@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '60900112',
                'ubi_us' => 'Ávila',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR044',
                'nom_us' => 'Vicente',
                'app_us' => 'Lemus',
                'apm_us' => 'Cornejo',
                'ema_us' => 'vicente.lemus@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '61011223',
                'ubi_us' => 'Soria',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR045',
                'nom_us' => 'Camila',
                'app_us' => 'Ocampo',
                'apm_us' => 'Maldonado',
                'ema_us' => 'camila.ocampo@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '62122334',
                'ubi_us' => 'Segovia',
                'tip_us' => 'usuario',
                'est_us' => 'baneado',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR046',
                'nom_us' => 'Rafael',
                'app_us' => 'Lozano',
                'apm_us' => 'Nava',
                'ema_us' => 'rafael.lozano@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '63233445',
                'ubi_us' => 'Teruel',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR047',
                'nom_us' => 'Verónica',
                'app_us' => 'Sarmiento',
                'apm_us' => 'Cepeda',
                'ema_us' => 'veronica.sarmiento@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '64344556',
                'ubi_us' => 'Huesca',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR048',
                'nom_us' => 'Ignacio',
                'app_us' => 'Pacheco',
                'apm_us' => 'Olvera',
                'ema_us' => 'ignacio.pacheco@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '65455667',
                'ubi_us' => 'Jaén',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR049',
                'nom_us' => 'Silvia',
                'app_us' => 'Fonseca',
                'apm_us' => 'Peralta',
                'ema_us' => 'silvia.fonseca@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '66566778',
                'ubi_us' => 'Zamora',
                'tip_us' => 'usuario',
                'est_us' => 'inactivo',
                'is_admin' => false,
            ],
            [
                'cod_us' => 'USR050',
                'nom_us' => 'Emilio',
                'app_us' => 'Espinoza',
                'apm_us' => 'Mojica',
                'ema_us' => 'emilio.espinoza@email.com',
                'pas_us' => Hash::make('12345678'),
                'tel_us' => '67677889',
                'ubi_us' => 'Cáceres',
                'tip_us' => 'usuario',
                'est_us' => 'activo',
                'is_admin' => false,
            ],
        ];
        
        foreach ($users as $user) {
            User::create($user);
        }
    }
}